FROM humble-ros-base:latest
 
# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]
 
# Install Git
RUN apt-get update && apt-get install -y git
 
# Create a ROS2 workspace and clone the ros repos
RUN source /opt/ros/humble/setup.bash \
 && mkdir -p /ros2_ws/src \
 && cd /ros2_ws/src \
 && git clone -b noetic-devel https://github.com/ROBOTIS-GIT/turtlebot3.git \

 
# Build the ROS2 workspace and ensure it's sourced
RUN source /opt/ros/humble/setup.bash \
 && cd ros2_ws \
 && colcon build --packages-select sine_pub
RUN echo "source /ros2_ws/devel/setup.bash" >> ~/.bashrc
 
# Set the working folder at startup
WORKDIR /turtlebot3_ws